services:
  postgres:
    image: postgres:16-alpine
    container_name: screening-postgres
    environment:
      POSTGRES_DB: keyword_screening
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  customer-analysis-postgres:
    image: postgres:16-alpine
    container_name: customer-analysis-postgres
    environment:
      POSTGRES_DB: customer_analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - customer_analysis_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:3.8.1
    container_name: pld-localstack
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

#  app:
#    build:
#      context: pld-transaction-screening
#      dockerfile: Dockerfile
#    container_name: screening-app
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/keyword_screening
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SERVER_PORT: 8081
#    depends_on:
#      postgres:
#        condition: service_healthy

volumes:
  postgres_data:
  customer_analysis_postgres_data:
  localstack_data:
